version: "3.9"

services:
   mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
   starwars:
    build: .
    container_name: star-wars-api
    restart: on-failure
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      PORT: "3000"
      LOG_LEVEL: "debug"
      MONGO_URI: mongodb://mongo:27017/planet?readPreference=primary&connectTimeoutMS=5000&socketTimeoutMS=5000
      MONGO_DB: planet
      MONGO_COLLECTION: planet
      MONGO_TIMEOUT: 1s
    depends_on:
      - mongo
