version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
  star-wars-api:
    build: .
    container_name: star-wars-api
    restart: on-failure
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      PORT: "8080"
      LOG_LEVEL: "debug"
      MONGO_URI: mongodb://mongo:27017/planet?readPreference=primary&connectTimeoutMS=5000&socketTimeoutMS=5000
      MONGO_DB: planet
      MONGO_COLLECTION: planet
      MONGO_TIMEOUT: 1s
    depends_on:
      - mongo

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    user: "1000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - prometheus
    ports:
      - 3000:3000
